version: '2'
services:
  db:    
    image: db:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres    
    ports:
    - "5555:5432"
    container_name: db
  api:
    image: api:latest
    environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_NAME=books_db
    - DB_PASSWORD=postgres 
    - DB_DIALECT=postgres
    ports:
    - 8081:8080
    container_name: api
    links:
    - db