version: '2.1'
services:
  db:    
    image: db:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres    
    ports:
    - "5555:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 2s
      timeout: 30s
      retries: 15
    container_name: db
  api:
    image: api:latest
    environment:
    - DB_HOST=db
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_NAME=books_db
    - DB_PASSWORD=postgres 
    - DB_DIALECT=postgres
    ports:
    - 8081:8080
    container_name: api
    links:
    - db
    depends_on:
      db:
        condition: service_healthy